import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "@kitajs/html/jsx-runtime";
import { VatRateDisplay } from '../VatRateDisplay.js';
export function VatBreakdownTable({ vatRateLines, vatDecs, t, nf }) {
    return (_jsxs("div", { class: "vat-breakdown", children: [_jsx("h4", { children: t('vatBreakdown') }), _jsxs("table", { class: "summary-table", children: [_jsx("thead", { children: _jsxs("tr", { children: [_jsx("th", { children: t('vatRate') }), _jsx("th", { class: "text-right", children: t('netAmount') }), _jsx("th", { class: "text-right", children: t('vatAmount') }), _jsx("th", { class: "text-right", children: t('grossAmount') })] }) }), _jsx("tbody", { children: vatRateLines.map(item => (_jsxs("tr", { children: [_jsx("td", { children: VatRateDisplay({ vatRate: item.vatRate, t, nf }) }), _jsxs("td", { class: "text-right", style: "white-space: nowrap;", children: [nf(item.vatRateNetData.vatRateNetAmount, vatDecs.net), item.vatRateNetData.vatRateNetAmountHUF &&
                                            item.vatRateNetData.vatRateNetAmountHUF !== item.vatRateNetData.vatRateNetAmount &&
                                            (_jsxs(_Fragment, { children: [_jsx("br", {}), _jsxs("small", { children: [nf(item.vatRateNetData.vatRateNetAmountHUF, vatDecs.net), " HUF"] })] }))] }), _jsxs("td", { class: "text-right", style: "white-space: nowrap;", children: [nf(item.vatRateVatData.vatRateVatAmount, vatDecs.vat), item.vatRateVatData.vatRateVatAmountHUF &&
                                            item.vatRateVatData.vatRateVatAmountHUF !== item.vatRateVatData.vatRateVatAmount &&
                                            (_jsxs(_Fragment, { children: [_jsx("br", {}), _jsxs("small", { children: [nf(item.vatRateVatData.vatRateVatAmountHUF, vatDecs.vat), " HUF"] })] }))] }), _jsx("td", { class: "text-right", style: "white-space: nowrap;", children: item.vatRateGrossData ? (_jsxs(_Fragment, { children: [nf(item.vatRateGrossData.vatRateGrossAmount, vatDecs.gross), item.vatRateGrossData.vatRateGrossAmountHUF &&
                                                item.vatRateGrossData.vatRateGrossAmountHUF !== item.vatRateGrossData.vatRateGrossAmount &&
                                                (_jsxs(_Fragment, { children: [_jsx("br", {}), _jsxs("small", { children: [nf(item.vatRateGrossData.vatRateGrossAmountHUF, vatDecs.gross), " HUF"] })] }))] })) : '-' })] }))).join('') })] })] }));
}
