const translations = {

  // 主标题
  invoice: "发票",
  header: "抬头",
  supplier: "供应商",
  customer: "客户",
  general: "基本信息",
  items: "项目明细",
  summary: "汇总",
  vatSummary: "增值税汇总",
  explanations: "缩写解释",
  fiscalRepresentative: "财务代表",
  conventionalInfo: "常规信息",
  additionalData: "附加数据",
  aggregateData: "汇总数据",

  // 发票头部数据
  invoiceNumber: "发票号码",
  invoiceIssueDate: "开具日期",
  invoiceDeliveryDate: "交付日期",
  invoiceDeliveryPeriod: "交付周期",
  invoiceAccountingDeliveryDate: "会计交付日期",
  paymentDate: "付款截止日期",
  paymentMethod: "付款方式",
  currencyCode: "货币",
  exchangeRate: "汇率",
  invoiceCategory: "发票类型",
  invoiceAppearance: "发票外观",
  deliveryDate: "交货日期",

  // 税务数据
  taxNumber: "税号",
  groupMemberTaxNumber: "集团成员税号",
  communityVatNumber: "社区增值税号",
  thirdStateTaxId: "第三国税务ID",
  customerVatStatus: "客户增值税状态",
  vatDomesticReverseCharge: "国内反向征税",
  vatExemption: "增值税豁免",
  vatOutOfScope: "范围外",
  individualExemption: "个人豁免",
  exciseLicenceNum: "消费税许可证号",

  // 指示器
  yes: "是",
  periodicalSettlement: "定期结算",
  smallBusinessIndicator: "小型企业指示器",
  utilitySettlementIndicator: "公用事业结算指示器",
  selfBillingIndicator: "自开票指示器",
  cashAccountingIndicator: "现金会计指示器",

  // 项目明细
  description: "描述",
  quantity: "数量",
  unitOfMeasure: "单位",
  unitPrice: "单价",
  net: "净额",
  vatType: "增值税类型",
  vat: "增值税",
  gross: "总额",
  modificationReference: "修改参考",
  originalInvoice: "原始发票",
  advancePayment: "预付款",

  // 产品费
  productFee: "产品费",
  productFeeOperation: "产品费操作",
  productFeeCode: "产品费代码",
  productFeeQuantity: "产品费数量",
  productFeeMeasuringUnit: "产品费单位",
  productFeeRate: "产品费率",
  productFeeAmount: "产品费金额",
  productChargeSum: "产品费总计",

  // 常规数据
  orderNumbers: "订单号",
  ekaerIds: "EKAER ID",
  deliveryNotes: "交货单",
  shippingDates: "发货日期",
  contractNumbers: "合同号",

  // 汇总
  netTotal: "净额总计",
  vatTotal: "增值税总计",
  grossTotal: "总额总计",

  // 利润方案类型
  marginSchemeIndicator: "利润方案",
  MARGIN: "利润",
  SECOND_HAND: "二手",
  ARTWORK: "艺术品",
  COLLECTOR_ITEM: "收藏品",
  TRAVEL_AGENCY: "旅行社",

  // 其他
  name: "名称",
  address: "地址",
  bankAccount: "银行账号",
  building: "建筑物",
  staircase: "楼梯",
  floor: "楼层",
  door: "门",
  lotNumber: "地块号",
  simplified: "简化",

  // 计量单位
  PIECE: "件",
  KILOGRAM: "千克",
  TON: "吨",
  KWH: "千瓦时",
  DAY: "天",
  HOUR: "小时",
  MINUTE: "分钟",
  MONTH: "月",
  LITER: "升",
  KILOMETER: "公里",
  CUBIC_METER: "立方米",
  METER: "米",
  LINEAR_METER: "延长米",
  CARTON: "纸箱",
  PACK: "包",
  OWN: "自定义",
  DARAB: "件",
  KG: "千克",

  // 付款方式
  PaymentMethodType_CASH: "现金",
  PaymentMethodType_TRANSFER: "转账",
  PaymentMethodType_CARD: "银行卡",
  PaymentMethodType_VOUCHER: "代金券",
  PaymentMethodType_OTHER: "其他",

  LineNatureIndicatorType_PRODUCT: "商品销售",
  LineNatureIndicatorType_SERVICE: "服务提供",
  LineNatureIndicatorType_OTHER: "其他，不可分类",

  CustomerVatStatusType_DOMESTIC: "国内增值税主体",
  CustomerVatStatusType_OTHER: "其他（国内非增值税主体，非自然人，国外增值税主体和国外非增值税主体，非自然人）",
  CustomerVatStatusType_PRIVATE_PERSON: "非增值税主体（国内或国外）自然人",

  ProductCodeCategoryType_VTSZ: "海关编码（HS编码）",
  ProductCodeCategoryType_SZJ: "服务清单编号",
  ProductCodeCategoryType_KN: "CN编码（联合命名法，2658/87/EGK法规附件I）",
  ProductCodeCategoryType_AHK: "2016年LXVIII号消费税法案定义的电子消费税管理参考代码",
  ProductCodeCategoryType_CSK: "根据343/2011政府法令(XII.29)附件1A)条款的包装材料产品目录代码",
  ProductCodeCategoryType_KT: "根据343/2011政府法令(XII.29)附件1B)条款的环保产品代码",
  ProductCodeCategoryType_EJ: "建筑物清单编号",
  ProductCodeCategoryType_TESZOR: "产品与服务分类系统(TESZOR)产品代码 - 451/2008/EC法规",
  ProductCodeCategoryType_OWN: "企业自定义产品代码",
  ProductCodeCategoryType_OTHER: "其他产品代码",

  // missing translations
  invoiceDetail: "发票详细信息",
  InvoiceCategoryType_NORMAL: "普通发票",
  PAPER: "纸质",
  productCode: "产品代码",
  vatRate: "增值税率",
  PRODUCT: "产品",
  vatPercentage: "增值税百分比",
  InvoiceCategoryType_SIMPLIFIED: "简化发票",
  vatContent: "增值税含量",
  SERVICE: "服务",
  referencesToOtherLines: "关联行参考",
  OTHER: "其他",
  vatDomesticReverseCharge_TRUE: "国内反向征收增值税（是）",
  MarginSchemeType_SECOND_HAND: "二手商品利润率方案",
  InvoiceCategoryType_AGGREGATE: "汇总发票",
  aggregateInvoiceLineData: "汇总发票行数据",
  invoiceReference: "发票参考",
  originalInvoiceNumber: "原始发票号码",
  modifyWithoutMaster: "无主修改",
  modificationIndex: "修改索引",
  lineModification: "行修改",
  lineModificationReference_lineNumberReference: "行号参考",
  line_modification_type: "行修改类型",
  unit: "单位",
  rate: "费率",
  amount: "金额",
  productFeeTakeoverData: "产品费承担数据",
  TakeoverType_02_b: "承担类型02_b",
  productFeeSummary: "产品费汇总",
  DEPOSIT: "存入",
  batchInvoice: "批量发票",
  batchIndex: "批量索引",

};

module.exports = { translations };