const translations = {
  invoice: "Invoice",
  header: "Header",
  supplier: "Supplier",
  customer: "Customer",
  general: "General data",
  items: "Items",
  summary: "Summary",
  vatSummary: "VAT summary",
  explanations: "Explanations",
  fiscalRepresentative: "Fiscal representative",
  conventionalInfo: "Conventional information",
  additionalData: "Additional data",
  aggregateData: "Aggregate data",
  invoiceNumber: "Invoice number",
  invoiceIssueDate: "Issue date",
  invoiceDeliveryDate: "Delivery date",
  invoiceDeliveryPeriod: "Delivery period",
  invoiceAccountingDeliveryDate: "Accounting delivery date",
  paymentDate: "Payment deadline",
  paymentMethod: "Payment method",
  currencyCode: "Currency",
  exchangeRate: "Exchange rate",
  invoiceCategory: "Invoice type",
  invoiceAppearance: "Invoice appearance",
  deliveryDate: "Delivery date",
  taxNumber: "Tax number",
  groupMemberTaxNumber: "Group member tax number",
  communityVatNumber: "Community VAT number",
  thirdStateTaxId: "Third state tax ID",
  customerVatStatus: "Customer VAT status",
  individualExemption: "Individual exemption",
  exciseLicenceNum: "Excise license number",
  vatPercentage: "The applied tax rate - VAT Act § 169 j)",
  vatContent: "VAT content in case of simplified invoice",
  vatExemption: "Marking tax exemption - VAT Act § 169 m)",
  vatOutOfScope: "Out of scope of the VAT law",
  vatDomesticReverseCharge: "Domestic reverse charge",
  vatDomesticReverseCharge_TRUE: "Belföldi fordított adózás",
  marginSchemeIndicator: "Margin scheme",
  MarginSchemeType_TRAVEL_AGENCY: "Travel agencies",
  MarginSchemeType_SECOND_HAND: "Second hand goods",
  MarginSchemeType_ARTWORK: "Artwork",
  MarginSchemeType_ANTIQUES: "Antiques",
  vatAmountMismatch: "Cases of mismatching tax base and levied tax",
  noVatCharge: "No VAT charged under section 17",
  periodicalSettlement: "Periodical settlement",
  smallBusinessIndicator: "Small business indicator",
  utilitySettlementIndicator: "Utility settlement indicator",
  selfBillingIndicator: "Self billing indicator",
  cashAccountingIndicator: "Cash accounting indicator",
  description: "Description",
  quantity: "Quantity",
  unitOfMeasure: "Unit",
  unitPrice: "Unit price",
  net: "Net",
  vatRate: "VAT Rate",
  vat: "VAT",
  gross: "Gross",
  productCode: "Product code",
  modificationReference: "Modification reference",
  originalInvoice: "Original invoice",
  advancePayment: "Advance payment",
  productFeeSummary: "Product fee summary",
  productFee: "Product fee",
  productFeeOperation: "Product fee operation",
  productFeeCode: "Product fee code",
  productFeeQuantity: "Product fee quantity",
  productFeeMeasuringUnit: "Product fee unit",
  productFeeRate: "Product fee rate",
  productFeeAmount: "Product fee amount",
  productChargeSum: "Product charge sum",
  orderNumbers: "Order numbers",
  ekaerIds: "EKAER IDs",
  deliveryNotes: "Delivery notes",
  shippingDates: "Shipping dates",
  contractNumbers: "Contract numbers",
  netTotal: "Net total",
  vatTotal: "VAT total",
  grossTotal: "Gross total",
  name: "Name",
  address: "Address",
  bankAccount: "Bank account",
  building: "Building",
  staircase: "Staircase",
  floor: "Floor",
  door: "Door",
  lotNumber: "Lot number",
  simplified: "Simplified",
  PIECE: "piece",
  KILOGRAM: "kg",
  TON: "ton",
  KWH: "kWh",
  DAY: "day",
  HOUR: "hour",
  MINUTE: "minute",
  MONTH: "month",
  LITER: "liter",
  KILOMETER: "km",
  CUBIC_METER: "m³",
  METER: "m",
  LINEAR_METER: "linear meter",
  CARTON: "carton",
  PACK: "pack",
  OWN: "own",
  DARAB: "piece",
  KG: "kg",
  PaymentMethodType_CASH: "Cash",
  PaymentMethodType_TRANSFER: "Transfer",
  PaymentMethodType_CARD: "Card",
  PaymentMethodType_VOUCHER: "Voucher",
  PaymentMethodType_OTHER: "Other",
  LineNatureIndicatorType_PRODUCT: "Supply of goods",
  LineNatureIndicatorType_SERVICE: "Supply of services",
  LineNatureIndicatorType_OTHER: "Other, non-qualifiable",
  CustomerVatStatusType_DOMESTIC: "Domestic VAT subject",
  CustomerVatStatusType_OTHER:
    "Other (domestic non-VAT subject, non-natural person, foreign VAT subject and foreign non-VAT subject, non-natural person)",
  CustomerVatStatusType_PRIVATE_PERSON: "Non-VAT subject (domestic or foreign) natural person",
  ProductCodeCategoryType_VTSZ: "Customs tariff number CTN",
  ProductCodeCategoryType_SZJ: "Business service list number BSL",
  ProductCodeCategoryType_KN: "CN code (Combined Nomenclature, 2658/87/ECC Annex I)",
  ProductCodeCategoryType_AHK:
    "Administrative reference code of e-TKO defined in the Act LXVIII of 2016 on Excise Duties",
  ProductCodeCategoryType_CSK:
    "Packaging product catalogue code of the product according to the Title A) in the Schedule No.1 of the Government Decree No. 343/2011. (XII. 29.)",
  ProductCodeCategoryType_KT:
    "Environmental protection product code of the product according to the Title B) in the Schedule No.1 of the Government Decree No. 343/2011. (XII. 29.)",
  ProductCodeCategoryType_EJ: "Classification of Inventory of Construction",
  ProductCodeCategoryType_TESZOR:
    "Product code according to the TESZOR (Hungarian Classification of Goods and Services), Classification of Product by Activity, CPA - regulation 451/2008/EC",
  ProductCodeCategoryType_OWN: "The own product code of the enterprise",
  ProductCodeCategoryType_OTHER: "Other product code",

  // missing translations
  invoiceDetail: "Invoice details",
  InvoiceCategoryType_NORMAL: "Normal invoice",
  PAPER: "Paper-based",
  PRODUCT: "Product",
  InvoiceCategoryType_SIMPLIFIED: "Simplified invoice",
  yes: "Yes",
  SERVICE: "Service",
  referencesToOtherLines: "References to other lines",
  SECOND_HAND: "Second-hand goods",
  OTHER: "Other",
  InvoiceCategoryType_AGGREGATE: "Aggregate invoice",
  aggregateInvoiceLineData: "Aggregate invoice line data",
  invoiceReference: "Invoice reference",
  originalInvoiceNumber: "Original invoice number",
  modifyWithoutMaster: "Modify without master",
  modificationIndex: "Modification index",
  lineModification: "Line modification",
  lineModificationReference_lineNumberReference: "Line number reference",
  line_modification_type: "Line modification type",
  unit: "unit",
  rate: "rate",
  amount: "amount",
  productFeeTakeoverData: "Product fee takeover data",
  TakeoverType_02_b: "Takeover type 02_b",
  DEPOSIT: "Deposit",
  batchInvoice: "Batch invoice",
  batchIndex: "Batch index",
};

module.exports = { translations };
