#!/usr/bin/env node
/**
 * Build-time asset inliner.
 * Generates:
 *   src/styles/cssInlined.ts   – CSS tartalmak string literálként
 *   src/i18n/translations.ts   – fordítási JSON objektumok statikusan
 *
 * Futtatás: node scripts/inline-assets.mjs
 * A `build` script automatikusan meghívja.
 *
 * Téma-konvenció (lásd README "Theme selection from XML"):
 *   - `invoice-styles.css` a base stílus (mindig beágyazva).
 *   - `invoice-<id>.css` fájlok a témák (delták: a base UTÁN fűzve).
 *   - Az XML-tag `I90000_IDTOHTMLDATA__CSS__<ID>` az <ID>-t kisbetűsítve
 *     oldja fel. Új téma = új `invoice-<id>.css` fájl, rebuild után
 *     automatikusan elérhető (nincs kézi regisztráció).
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

/** Fájl tartalmát escape-eli TypeScript template literal-ba. */
function escapeForTemplateLiteral(str) {
  return str.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

/** Fájl beolvasása, hiba esetén figyelmeztetés + üres string. */
function readSrc(relPath) {
  const abs = resolve(root, 'src', relPath);
  try {
    return readFileSync(abs, 'utf8');
  } catch {
    console.warn(`[inline-assets] WARNING: could not read ${abs}`);
    return '';
  }
}

// ── package.json verzió ──────────────────────────────────────────────────────
const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
const version = pkg.version ?? '0.0.0';

// ── CSS fájlok (generikus téma-felderítés) ────────────────────────────────────
// Base: invoice-styles.css. Témák: minden további invoice-<id>.css,
// ahol az <id> [a-z0-9_-]{1,32} (kisbetűsítve). Ismeretlen/más nevű
// fájlok figyelmen kívül hagyva.
const THEME_FILE_RE = /^invoice-([a-z0-9_-]{1,32})\.css$/;
const BASE_CSS_FILE = 'invoice-styles.css';

const invoiceStylesCss = readSrc(`styles/${BASE_CSS_FILE}`);

let themeFiles = [];
try {
  themeFiles = readdirSync(resolve(root, 'src/styles'), 'utf8')
    .filter((f) => f !== BASE_CSS_FILE && THEME_FILE_RE.test(f))
    .sort();
} catch {
  console.warn('[inline-assets] WARNING: could not list src/styles');
}

const themeEntries = [];
for (const file of themeFiles) {
  const id = file.match(THEME_FILE_RE)[1].toLowerCase();
  const css = readSrc(`styles/${file}`);
  themeEntries.push({ id, css });
  console.log(`[inline-assets] Theme found: ${id} (${file}, ${css.length} chars)`);
}

const themeMapBody = themeEntries
  .map(({ id, css }) => `  ${JSON.stringify(id)}: \`${escapeForTemplateLiteral(css)}\`,`)
  .join('\n');

// Visszafelé kompatibilitás: a korábbi kézi `invoiceCompactCss` export
// megmarad (a compact téma aliasa, ha létezik).
const cssOut = `// AUTO-GENERATED by scripts/inline-assets.mjs – do not edit manually.
/* eslint-disable */

export const PACKAGE_VERSION = ${JSON.stringify(version)};

export const invoiceStylesCss = \`${escapeForTemplateLiteral(invoiceStylesCss)}\`;

/**
 * Bundolt témák: invoice-<id>.css delták (a base invoice-styles.css UTÁN
 * fűzendők). Kulcs az <ID> kisbetűsítve (pl. "compact").
 * Új téma = új invoice-<id>.css fájl + rebuild, nincs kézi regisztráció.
 */
export const THEME_CSS: Record<string, string> = {
${themeMapBody}
};

/** @deprecated Használd a THEME_CSS["compact"]-ot. Megtartva kompatibilitás miatt. */
export const invoiceCompactCss = THEME_CSS["compact"] ?? "";
`;

mkdirSync(resolve(root, 'src/styles'), { recursive: true });
writeFileSync(resolve(root, 'src/styles/cssInlined.ts'), cssOut, 'utf8');
console.log('[inline-assets] Generated src/styles/cssInlined.ts');

// ── i18n fordítások ──────────────────────────────────────────────────────────
const locales = ['hu', 'en'];
const translationMap = {};
for (const locale of locales) {
  const raw = readSrc(`i18n/${locale}.json`);
  try {
    translationMap[locale] = JSON.parse(raw);
  } catch {
    console.warn(`[inline-assets] WARNING: could not parse i18n/${locale}.json`);
    translationMap[locale] = {};
  }
}

const i18nOut = `// AUTO-GENERATED by scripts/inline-assets.mjs – do not edit manually.
/* eslint-disable */

export const TRANSLATIONS: Record<string, Record<string, string>> = ${JSON.stringify(translationMap, null, 2)};
`;

mkdirSync(resolve(root, 'src/i18n'), { recursive: true });
writeFileSync(resolve(root, 'src/i18n/translations.ts'), i18nOut, 'utf8');
console.log('[inline-assets] Generated src/i18n/translations.ts');
